"""Baseline: the schema as it stood when migrations were introduced (PLAN.md WS-6).

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-24

Autogenerated from `nethub/models.py`, then frozen. Never edit this file to
match a later model change -- write a new migration. Everything here is a
literal on purpose: a migration that imported the models would change meaning
whenever they did.

The terminal-status trigger is the one piece autogenerate cannot see: the
models attach it with an `after_create` DDL event, so it is written out
below. `tests/test_schema.py` builds a database from these migrations and one
from `create_all()` and asserts they match, trigger included.
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None

#: §7.3: a job row in a terminal status is never written to again.
TERMINAL_TRIGGER = """
CREATE TRIGGER upgrade_phase_jobs_terminal_immutable
BEFORE UPDATE ON upgrade_phase_jobs
FOR EACH ROW WHEN OLD.status IN ('abandoned', 'cancelled', 'expired', 'failed', 'succeeded', 'timed_out')
BEGIN
    SELECT RAISE(ABORT,
        'upgrade_phase_jobs row is terminal and must not be updated');
END;
"""


def upgrade():
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('device_username', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('script', 'config', 'image', name='artifact_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('bundle_key', sa.String(length=80), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('sha512', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('state', sa.Enum('staged', 'published', 'superseded', name='artifact_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('bytes_state', sa.Enum('present', 'pruned', name='artifact_bytes_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('bytes_pruned_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index('uq_artifact_bundle_key', ['platform', 'bundle_key'], unique=True, sqlite_where=sa.text("kind = 'image' AND state = 'published'"))
        batch_op.create_index('uq_artifact_filename_live', ['filename'], unique=True, sqlite_where=sa.text("state IN ('staged', 'published')"))

    op.create_table('device_host_key_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ansible_host', sa.String(length=64), nullable=False),
    sa.Column('action', sa.Enum('confirmed', 'deleted', name='hostkey_audit_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('key_type', sa.String(length=32), nullable=False),
    sa.Column('fingerprint_sha256', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_host_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ansible_host', sa.String(length=64), nullable=False),
    sa.Column('key_type', sa.String(length=32), nullable=False),
    sa.Column('fingerprint_sha256', sa.String(length=64), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ansible_host')
    )
    op.create_table('host_key_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ansible_host', sa.String(length=64), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'abandoned', name='hostkey_scan_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('key_type', sa.String(length=32), nullable=True),
    sa.Column('fingerprint_sha256', sa.String(length=64), nullable=True),
    sa.Column('error_summary', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('runner_instance_id', sa.String(length=36), nullable=True),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upgrade_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('device_username_used', sa.String(length=80), nullable=False),
    sa.Column('request_document', sa.Text(), nullable=False),
    sa.Column('request_sha512', sa.String(length=128), nullable=False),
    sa.Column('state', sa.Enum('pre_checking', 'awaiting_approval', 'running', 'completed', 'failed', 'cancelled', 'expired', name='run_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('awaiting_phase', sa.Enum('precheck', 'stage', 'activate', 'verify', 'cleanup', name='awaiting_phase', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('gate_expires_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_requested_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cancel_requested_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upgrade_phase_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('precheck', 'stage', 'activate', 'verify', 'cleanup', name='job_phase', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'timed_out', 'abandoned', 'cancelled', 'expired', name='job_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('failure_stage', sa.Enum('credential', 'connect', 'hostkey', 'privilege', 'precheck', 'transfer', 'checksum', 'install', 'reload', 'postcheck', name='phase_failure_stage', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('error_summary', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('runner_instance_id', sa.String(length=36), nullable=True),
    sa.Column('log_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['upgrade_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'phase', 'attempt', name='uq_phase_job_attempt')
    )
    op.execute(TERMINAL_TRIGGER)
    op.create_table('upgrade_run_hosts',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ansible_host', sa.String(length=64), nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=True),
    sa.Column('bundle_key', sa.String(length=80), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('sha512', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('flash_dir', sa.String(length=64), nullable=False),
    sa.Column('config_backup_path', sa.String(length=255), nullable=True),
    sa.Column('reported_version_pre', sa.String(length=32), nullable=True),
    sa.Column('reported_version_post', sa.String(length=32), nullable=True),
    sa.Column('state', sa.Enum('pending', 'precheck_ok', 'staged', 'activated', 'verified', 'failed', 'skipped', name='host_state', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('last_phase', sa.Enum('precheck', 'stage', 'activate', 'verify', 'cleanup', name='host_last_phase', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('error_summary', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['upgrade_runs.id'], ),
    sa.PrimaryKeyConstraint('run_id', 'hostname')
    )
    op.create_table('upgrade_host_phase_results',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('phase', sa.Enum('precheck', 'stage', 'activate', 'verify', 'cleanup', name='result_phase', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('failure_stage', sa.Enum('credential', 'connect', 'hostkey', 'privilege', 'precheck', 'transfer', 'checksum', 'install', 'reload', 'postcheck', name='result_failure_stage', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('error_summary', sa.String(length=500), nullable=True),
    sa.Column('scp_restore_confirmed', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id', 'hostname'], ['upgrade_run_hosts.run_id', 'upgrade_run_hosts.hostname'], name='fk_result_run_host'),
    sa.ForeignKeyConstraint(['run_id', 'phase', 'attempt'], ['upgrade_phase_jobs.run_id', 'upgrade_phase_jobs.phase', 'upgrade_phase_jobs.attempt'], name='fk_result_phase_job'),
    sa.PrimaryKeyConstraint('run_id', 'hostname', 'phase', 'attempt')
    )


def downgrade():
    # There is nothing below the baseline to go back to, and dropping every
    # table is not a downgrade. Going back to an older NetHub means restoring
    # the backup taken before upgrading.
    raise NotImplementedError('0001_baseline cannot be downgraded; restore a backup')
