---
## in  -- target_image, target_image_size, target_image_size_kb (see
##        tasks/resolve_target_bundle.yml), iosxe_facts_flash_dir_info (set
##        by the iosxe_facts role)
## out -- a task failure if there isn't enough free space

- name: Print image sizes
  tags: pre-check, disk_check, image-check, image-copy, install
  ansible.builtin.debug:
    msg: >-
      Target image size is {{ target_image_size }} bytes ({{ target_image_size_kb }} KB).
      Total available in the device is {{ iosxe_facts_flash_dir_info['spacefree_kb'] }} KB

- name: Assert Enough Disk Space Available
  tags: image-copy, install
  ansible.builtin.assert:
    quiet: false
    success_msg: "Enough disk spcae available to accommodate target image."
    fail_msg: 'Not enough disk space available for the target image!'
    that:
      - "iosxe_facts_flash_dir_info['spacefree_kb'] | int > target_image_size_kb | int"
