## in  - file_system_name
## out - iosxe_facts_flash_dir_info,
##       populated ansible_facts dictionary
---
- name: Gather IOS XE device facts
  tags: [pre-check, check-version, install, upgrade]
  cisco.ios.ios_facts:
    gather_subset: all

- name: Set flash directory facts
  tags: [pre-check, check-version, install, upgrade]
  ansible.builtin.set_fact:
    iosxe_facts_flash_dir_info: "{{ ansible_facts['net_filesystems_info'][file_system_name] }}"

- name: Basic Facts for "{{ inventory_hostname }}"
  tags: [pre-check, check-version, install]
  ansible.builtin.debug:
    msg:
      - "Device Mode: {{ ansible_facts['net_model'] }}"
      - "Serial Number: {{ ansible_facts['net_serialnum'] }}"
      - "IOS-XE Version: {{ ansible_facts['net_version'] }}"
      - "IOS-XE Image: {{ ansible_facts['net_image'] }}"
      - "Free Memory (Mb): {{ ansible_facts['net_memfree_mb'] }}"
      - "Total Memory (Mb): {{ ansible_facts['net_memtotal_mb'] }}"
      - "Free Diskspace (kb): {{ iosxe_facts_flash_dir_info['spacefree_kb'] }}"
      - "Total Diskspace (kb): {{ iosxe_facts_flash_dir_info['spacetotal_kb'] }}"
