-- create_all() output of nethub/models.py at commit c76688d:
--   feat: dispatch host-key scanning to the sibling and bind confirm to it (WS-6.2b/6.3/6.4)
-- Generated by running db.create_all() against an empty SQLite file from a
-- checkout of that commit. Evidence of what a pre-migration database looks
-- like (tests/test_schema.py adopts it); do not edit to make a test pass.
CREATE TABLE user (
	id INTEGER NOT NULL, 
	username VARCHAR(80) NOT NULL, 
	password_hash VARCHAR(255) NOT NULL, 
	device_username VARCHAR(80), 
	created_at DATETIME, 
	failed_logins INTEGER NOT NULL, 
	locked_until DATETIME, 
	PRIMARY KEY (id), 
	UNIQUE (username)
);
CREATE TABLE artifacts (
	id INTEGER NOT NULL, 
	kind VARCHAR(6) NOT NULL, 
	platform VARCHAR(32) NOT NULL, 
	bundle_key VARCHAR(80) NOT NULL, 
	filename VARCHAR(255) NOT NULL, 
	sha512 VARCHAR(128) NOT NULL, 
	file_size BIGINT NOT NULL, 
	storage_path VARCHAR(500) NOT NULL, 
	version VARCHAR(32) NOT NULL, 
	state VARCHAR(10) NOT NULL, 
	superseded_by_id INTEGER, 
	bytes_state VARCHAR(7) NOT NULL, 
	bytes_pruned_at DATETIME, 
	uploaded_by INTEGER, 
	uploaded_at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT artifact_kind CHECK (kind IN ('script', 'config', 'image')), 
	CONSTRAINT artifact_state CHECK (state IN ('staged', 'published', 'superseded')), 
	FOREIGN KEY(superseded_by_id) REFERENCES artifacts (id), 
	CONSTRAINT artifact_bytes_state CHECK (bytes_state IN ('present', 'pruned')), 
	FOREIGN KEY(uploaded_by) REFERENCES user (id)
);
CREATE UNIQUE INDEX uq_artifact_filename_live ON artifacts (filename) WHERE state IN ('staged', 'published');
CREATE UNIQUE INDEX uq_artifact_bundle_key ON artifacts (platform, bundle_key) WHERE kind = 'image' AND state = 'published';
CREATE TABLE device_host_keys (
	id INTEGER NOT NULL, 
	ansible_host VARCHAR(64) NOT NULL, 
	key_type VARCHAR(32) NOT NULL, 
	fingerprint_sha256 VARCHAR(64) NOT NULL, 
	first_seen_at DATETIME NOT NULL, 
	confirmed_by INTEGER, 
	confirmed_at DATETIME, 
	PRIMARY KEY (id), 
	UNIQUE (ansible_host), 
	FOREIGN KEY(confirmed_by) REFERENCES user (id)
);
CREATE TABLE host_key_scans (
	id INTEGER NOT NULL, 
	ansible_host VARCHAR(64) NOT NULL, 
	requested_by INTEGER NOT NULL, 
	status VARCHAR(9) NOT NULL, 
	key_type VARCHAR(32), 
	fingerprint_sha256 VARCHAR(64), 
	error_summary VARCHAR(500), 
	created_at DATETIME NOT NULL, 
	started_at DATETIME, 
	finished_at DATETIME, 
	runner_instance_id VARCHAR(36), 
	consumed_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(requested_by) REFERENCES user (id), 
	CONSTRAINT hostkey_scan_status CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'abandoned'))
);
CREATE TABLE device_host_key_audit (
	id INTEGER NOT NULL, 
	ansible_host VARCHAR(64) NOT NULL, 
	action VARCHAR(9) NOT NULL, 
	key_type VARCHAR(32) NOT NULL, 
	fingerprint_sha256 VARCHAR(64) NOT NULL, 
	actor_id INTEGER NOT NULL, 
	at DATETIME NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT hostkey_audit_action CHECK (action IN ('confirmed', 'deleted')), 
	FOREIGN KEY(actor_id) REFERENCES user (id)
);
CREATE TABLE upgrade_runs (
	id INTEGER NOT NULL, 
	platform VARCHAR(32) NOT NULL, 
	submitted_by INTEGER NOT NULL, 
	device_username_used VARCHAR(80) NOT NULL, 
	shared_account_mode BOOLEAN NOT NULL, 
	image_transport_used VARCHAR(9) NOT NULL, 
	distribution_host_used VARCHAR(255), 
	request_document TEXT NOT NULL, 
	request_sha512 VARCHAR(128) NOT NULL, 
	state VARCHAR(17) NOT NULL, 
	awaiting_phase VARCHAR(8), 
	gate_expires_at DATETIME, 
	cancel_requested_at DATETIME, 
	cancel_requested_by INTEGER, 
	created_at DATETIME NOT NULL, 
	finished_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(submitted_by) REFERENCES user (id), 
	CONSTRAINT transport CHECK (image_transport_used IN ('push_scp', 'pull_sftp')), 
	CONSTRAINT run_state CHECK (state IN ('pre_checking', 'awaiting_approval', 'running', 'completed', 'failed', 'cancelled', 'expired')), 
	CONSTRAINT awaiting_phase CHECK (awaiting_phase IN ('precheck', 'stage', 'activate', 'verify', 'cleanup')), 
	FOREIGN KEY(cancel_requested_by) REFERENCES user (id)
);
CREATE TABLE upgrade_run_hosts (
	run_id INTEGER NOT NULL, 
	hostname VARCHAR(255) NOT NULL, 
	ansible_host VARCHAR(64) NOT NULL, 
	artifact_id INTEGER, 
	bundle_key VARCHAR(80), 
	filename VARCHAR(255) NOT NULL, 
	sha512 VARCHAR(128) NOT NULL, 
	version VARCHAR(32) NOT NULL, 
	file_size BIGINT NOT NULL, 
	flash_dir VARCHAR(64) NOT NULL, 
	config_backup_path VARCHAR(255), 
	reported_version_pre VARCHAR(32), 
	reported_version_post VARCHAR(32), 
	state VARCHAR(11) NOT NULL, 
	last_phase VARCHAR(8), 
	error_summary VARCHAR(500), 
	PRIMARY KEY (run_id, hostname), 
	FOREIGN KEY(run_id) REFERENCES upgrade_runs (id), 
	CONSTRAINT host_state CHECK (state IN ('pending', 'precheck_ok', 'staged', 'activated', 'verified', 'failed', 'skipped')), 
	CONSTRAINT host_last_phase CHECK (last_phase IN ('precheck', 'stage', 'activate', 'verify', 'cleanup'))
);
CREATE TABLE upgrade_phase_jobs (
	id INTEGER NOT NULL, 
	run_id INTEGER NOT NULL, 
	phase VARCHAR(8) NOT NULL, 
	attempt INTEGER NOT NULL, 
	approved_by INTEGER, 
	approved_at DATETIME, 
	status VARCHAR(9) NOT NULL, 
	failure_stage VARCHAR(10), 
	error_summary VARCHAR(500), 
	created_at DATETIME NOT NULL, 
	started_at DATETIME, 
	heartbeat_at DATETIME, 
	deadline_at DATETIME, 
	finished_at DATETIME, 
	runner_instance_id VARCHAR(36), 
	log_path VARCHAR(255), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_phase_job_attempt UNIQUE (run_id, phase, attempt), 
	FOREIGN KEY(run_id) REFERENCES upgrade_runs (id), 
	CONSTRAINT job_phase CHECK (phase IN ('precheck', 'stage', 'activate', 'verify', 'cleanup')), 
	FOREIGN KEY(approved_by) REFERENCES user (id), 
	CONSTRAINT job_status CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'timed_out', 'abandoned', 'cancelled', 'expired')), 
	CONSTRAINT phase_failure_stage CHECK (failure_stage IN ('credential', 'connect', 'hostkey', 'privilege', 'precheck', 'transfer', 'checksum', 'install', 'reload', 'postcheck'))
);
CREATE TRIGGER upgrade_phase_jobs_terminal_immutable
        BEFORE UPDATE ON upgrade_phase_jobs
        FOR EACH ROW WHEN OLD.status IN ('abandoned', 'cancelled', 'expired', 'failed', 'succeeded', 'timed_out')
        BEGIN
            SELECT RAISE(ABORT,
                'upgrade_phase_jobs row is terminal and must not be updated');
        END;
CREATE TABLE upgrade_host_phase_results (
	run_id INTEGER NOT NULL, 
	hostname VARCHAR(255) NOT NULL, 
	phase VARCHAR(8) NOT NULL, 
	attempt INTEGER NOT NULL, 
	status VARCHAR(40) NOT NULL, 
	failure_stage VARCHAR(10), 
	error_summary VARCHAR(500), 
	scp_restore_confirmed BOOLEAN, 
	started_at DATETIME, 
	finished_at DATETIME, 
	PRIMARY KEY (run_id, hostname, phase, attempt), 
	CONSTRAINT fk_result_phase_job FOREIGN KEY(run_id, phase, attempt) REFERENCES upgrade_phase_jobs (run_id, phase, attempt), 
	CONSTRAINT fk_result_run_host FOREIGN KEY(run_id, hostname) REFERENCES upgrade_run_hosts (run_id, hostname), 
	CONSTRAINT result_phase CHECK (phase IN ('precheck', 'stage', 'activate', 'verify', 'cleanup')), 
	CONSTRAINT result_failure_stage CHECK (failure_stage IN ('credential', 'connect', 'hostkey', 'privilege', 'precheck', 'transfer', 'checksum', 'install', 'reload', 'postcheck'))
);
